### ISSUE TITLE
AttributeError in running speech_encoder

### ISSUE THREAD

**Issue by kc-li** [lingjzhu/clap-ipa#3]
As phoneticians, we are eager to explore this exciting IPA forced alignment tool! However, some parts of the current README file are somewhat unclear, and I would like to ask for some clarifications.

Here is the code I am using to load and process the audio and IPA input (I specified a few more options based on warning options and other found examples):
```
import soundfile as sf
sample, _ = sf.read("/Users/kechun/Downloads/fa-test/ipa_test.wav")
audio_input = processor(sample, sampling_rate=16000, return_tensors='pt')

ipa_string = ['wo', 'laɪ', 'tsɹ̩', 't͡ʂʊŋ', 'kwo', 'ɪk', 'kom', 'œyt', 'ʃiːna']
ipa_input = tokenizer(ipa_string, padding=True,add_special_tokens=False,return_tensors='pt')
```

However, when I attempt to run the encoders on these inputs:

```
with torch.no_grad():
   speech_outputs = speech_encoder(audio_input)
   phone_outputs = phone_encoder(ipa_input)
```

I encounter the following error message:

```
Traceback (most recent call last):
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/transformers/feature_extraction_utils.py", line 93, in __getattr__
    return self.data[item]
           ~~~~~~~~~^^^^^^
KeyError: 'size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/clap-ipa/clap-ipa/clap/encoders.py", line 128, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/clap-ipa/clap-ipa/clap/WhisperEncoder.py", line 243, in forward
    input_features = self._mask_input_features(input_features, attention_mask=attention_mask)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/clap-ipa/clap-ipa/clap/WhisperEncoder.py", line 349, in _mask_input_features
    batch_size, hidden_size, sequence_length = input_features.size()
                                               ^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/transformers/feature_extraction_utils.py", line 95, in __getattr__
    raise AttributeError
AttributeError
```

It seems that there is an issue with the input_features when calling self._mask_input_features in the WhisperEncoder. Could you please advise me on what might be causing this error? Am I missing a step in the processing of the audio or IPA inputs?

Additionally, if the code runs successfully, what output should I expect? (e.g., Will there be a specific file generated, or should I expect model outputs in a certain format?)

Thank you for your help!

**Comment by kc-li** [comment]
Some further information:

Following some exmaples, I also tried to generate audio_input in this way (with `.input_features`):

```
audio_input = processor(sample, sampling_rate=16000, return_tensors='pt').input_features
```

And then calling the speech_encoder gives me the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/clap-ipa/clap-ipa/clap/encoders.py", line 128, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/miniconda3/envs/fa/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kechun/clap-ipa/clap-ipa/clap/WhisperEncoder.py", line 301, in forward
    expanded_attention_mask,
    ^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'expanded_attention_mask' where it is not associated with a value
```
How should I proceed?

**Comment by smfsamir** [comment]
Hi @kc-li, I'm one of the co-authors on the paper. Sorry for our delayed response, I missed the notification for this. 

Could you try the following (modifying your first example):

```
import soundfile as sf
sample, _ = sf.read("/Users/kechun/Downloads/fa-test/ipa_test.wav")
audio_input = processor(sample, sampling_rate=16000, return_tensors='pt', return_attention_mask=True)

ipa_string = ['wo', 'laɪ', 'tsɹ̩', 't͡ʂʊŋ', 'kwo', 'ɪk', 'kom', 'œyt', 'ʃiːna']
ipa_string = ''.join(ipa_string)
transcript_tokens = torch.tensor(tokenizer(ipa_string, return_attention_mask=False, return_length=True, return_token_type_ids=False, add_special_tokens=False)['input_ids'])

phone_features = phone_encoder(transcript_tokens.unsqueeze(0)).last_hidden_state.squeeze(0)
speech_features = speech_encoder(**audio_encoded, return_dict=True).last_hidden_state.squeeze(0)
```
Let me know if this works for you

**Comment by egorsmkv** [comment]
@smfsamir hello, is there a simple demo to run forced aligment?

**Comment by lingjzhu** [comment]
> [@smfsamir](https://github.com/smfsamir) hello, is there a simple demo to run forced aligment?

I aim to provide a demo this weekend. Sorry it's long over due. My current job does not allow me to devote time to do serious coding.

**Comment by egorsmkv** [comment]
> > [@smfsamir](https://github.com/smfsamir) hello, is there a simple demo to run forced aligment?
> 
> I aim to provide a demo this weekend. Sorry it's long over due. My current job does not allow me to devote time to do serious coding. 

Thank you. I'll be waiting and have a good day!

**Comment by smfsamir** [comment]
Hi @egorsmkv 

I have added an example of how to do zero-shot keyword spotting in `example.ipynb`. It uses the recently uploaded `sample.wav` recording. Let me know if this works for you.

**Comment by egorsmkv** [comment]
@smfsamir  I have tried to run the notebook. A few thoughts:

1. It does not have clap-ipa installation code.
2. If I run on CUDA, not all code-cells have the same device (here's my fixed notebook - https://drive.google.com/file/d/1RGvw2oCRKQ5Zc73Ftu8aj-mRmfp5tR_3/view?usp=sharing )

**Comment by smfsamir** [comment]
Thanks!

**Comment by lingjzhu** [comment]
> [@smfsamir](https://github.com/smfsamir) hello, is there a simple demo to run forced aligment?

Sorry for the delay. I have added a demo for forced alignment at: `forced_alignment_example.ipynb`. The phone-level alignment is mediocre, but the word-level alignment is pretty OK.

**Comment by egorsmkv** [comment]
thank you very much
